version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wtf-viniplay_app_1
      APP_PORT: 8998

  app:
    image: ardovini/viniplay:0.11.0@sha256:60a7d15a4c6171fa3e778e1a9b4c54442fbb0e463028aefa87cf5e2b7be37bfc
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
    env_file:
      - ${APP_DATA_DIR}/.env
